### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Tyke0318** [hyunyongPark/StyleClassifier#1]
Could you please provide the dataset or the .pth file. Orz.

**Comment by hyunyongPark** [comment]
Sorry, 
I don't currently have the weight file or Training dataset of the project.

However, you can try scratch training based on a similar dataset. 
The link to the open dataset is as follows.
[AIHub-kfashion](https://aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=realm&dataSetSn=51)

Like my project, there is a main/substyle in this data, which enables multi-labeling.
